# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChoosePatient.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChoosePatient(object):
    def setupUi(self, ChoosePatient):
        ChoosePatient.setObjectName("ChoosePatient")
        ChoosePatient.setWindowModality(QtCore.Qt.ApplicationModal)
        ChoosePatient.resize(502, 325)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        ChoosePatient.setFont(font)
        ChoosePatient.setAutoFillBackground(False)
        ChoosePatient.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.comboBox_patient = QtWidgets.QComboBox(ChoosePatient)
        self.comboBox_patient.setGeometry(QtCore.QRect(50, 110, 411, 31))
        self.comboBox_patient.setObjectName("comboBox_patient")
        self.label = QtWidgets.QLabel(ChoosePatient)
        self.label.setGeometry(QtCore.QRect(80, 50, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(ChoosePatient)
        self.pushButton.setGeometry(QtCore.QRect(200, 230, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.comboBox_study = QtWidgets.QComboBox(ChoosePatient)
        self.comboBox_study.setGeometry(QtCore.QRect(50, 170, 411, 31))
        self.comboBox_study.setObjectName("comboBox_study")

        self.retranslateUi(ChoosePatient)
        QtCore.QMetaObject.connectSlotsByName(ChoosePatient)

    def retranslateUi(self, ChoosePatient):
        _translate = QtCore.QCoreApplication.translate
        ChoosePatient.setWindowTitle(_translate("ChoosePatient", "Вибір пацієнта та обстеження"))
        self.label.setText(_translate("ChoosePatient", "Будь-ласка, оберіть пацієнта"))
        self.pushButton.setText(_translate("ChoosePatient", "OK"))
